### ISSUE TITLE
App crash

### ISSUE THREAD

**Issue by brianvychow** [bartbols/SASHIMI#3]
App crashed after I click track a couple of times (as in track more than the slices of the image). E.g. image has 290 slices, but I click track about 3-5 times at 290.
I did not notice the pop-up error window because it didn't appear in front, but instead behind the app.

This is when I have all 290 slices with objects. I couldn't replicate the crash when there's only a few slices. Lost all 290 objects without being saved.

**Comment by brianvychow** [comment]
Looks like similar pattern when i try to load unmatched object slices. Error pop up and i couldn't retrieve the app. The only workaround is close the app and reopen it.

So far tested in shashimi 2019 app on MacOS Catalina 10.15.4

**Comment by bartbols** [comment]
New dialog boxes are used in version 1.1 which should resolve this issue.
