### ISSUE TITLE
The crosshair cursor only works if you click on it and pull

### ISSUE THREAD

**Issue by brianvychow** [bartbols/SASHIMI#4]
Unlike itksnap where you can click anyway on the image, the crosshair cursor will follow the clicked point.

In this version (tested in mac), the crosshair needs to be exactly clicked on before you can pull them.

**Comment by bartbols** [comment]
This is the intended behaviour. There are two ways to move the crosshair:
1) Hold the shift button and click on a location in the image to move the crosshair to the clicked location.
2) Hover your mouse over the crosshair and drag it around.

**Comment by brianvychow** [comment]
Great! The shift button works on mac too. I will close this issue then.
