### ISSUE TITLE
'A' shortkey in Mac

### ISSUE THREAD

**Issue by brianvychow** [bartbols/SASHIMI#6]
When I click on the label (say purple), then I click "add", this works fine.

But when I try to use shortkey "A" instead of "add" button, the object will appear as normal but the label name will also be appended with "a". So "gastrocnemius lateralis" becomes "gastrocnemius lateralis**a**"

**Comment by bartbols** [comment]
Yes, this is the same in Windows and it is a bit annoying. By clicking on label in the label table, you open the label name for editing as well as selecting the label. When you press 'a' directly after selecting a label, the name will be edited (by adding the pressed key, in this case 'a', to the label name. To stop this from happening, after you have selected a label from the label table, click somewhere in the image first, then press 'a'.
