### ISSUE TITLE
Image size error

### ISSUE THREAD

**Issue by brianvychow** [bartbols/SASHIMI#7]
![image](https://user-images.githubusercontent.com/7777982/82424806-0a4ace00-9ac9-11ea-80dc-571da7beb9bf.png)

![image](https://user-images.githubusercontent.com/7777982/82425126-73324600-9ac9-11ea-8676-5e277cc813c0.png)

The image suddenly zooms out all the way until it becomes smaller than a dot and there is no way to reset the view or scroll back the size. The error message as attached. This is using Windows standalone.

**Comment by brianvychow** [comment]
Just found the culprit. It was the thumb scroll (side scroll) of my mouse (only this mouse has thumb scroll). No matter which direction I scroll, it will continue to zoom out and I couldn't get it bigger again even using the standard vertical scroll. A reset view button will be helpful although not urgent.

**Comment by bartbols** [comment]
Good that you found out the problem. You can always reset the view by switching to another plane and then switching back to the plane you were working on.
